### ISSUE TITLE
password_reset_from_key not working [bug]

### ISSUE THREAD

**Issue by jonsimington** [siggame/webserver#46]
When attempting to reset password via the link that is sent to the user from the password reset form found at `accounts/password/reset/`, this error is produced:

`Attribute Error: 'PasswordResetFromKeyView' object has no attribute 'request'`

file of interest: `webserver/var/eggs/django_allauth-0.13.0-py2.7.egg/allauth/account/views.py`

**Comment by michaelwisely** [comment]
The production site does it too... I'll look into it.

**Comment by michaelwisely** [comment]
I'm not thrilled about that solution, but it works. I'd rather patch a released version of the app than use a random commit from their source. If there's a smarter way to fix it, that'd be even better.

Since buildout applies a patch to allauth, it's necessary to run `make` or `buildout` to get it to work.
