### ISSUE TITLE
Blog layout improvements.

### ISSUE THREAD

**Issue by ShaneBurkhart** [siggame/webserver#49]
Space the blog posts.  And make wells smaller.

**Comment by michaelwisely** [comment]
We've already talked about it, but the style for the blog is in [this repository](https://github.com/siggame/webserver-zinnia-theme). [Zinnia](http://docs.django-blog-zinnia.com/en/v0.12.3/) has a number of themes, including a [bootstrap](https://github.com/Fantomas42/zinnia-theme-bootstrap) one.

You should be able to clone [siggame/webserver-zinnia-theme](https://github.com/siggame/webserver-zinnia-theme) and run make, just like with the webserver's source. The only difference is that the executable created is called bin/demo instead of bin/django.
