### ISSUE TITLE
Make ineligibility extremely clear

### ISSUE THREAD

**Issue by jonsimington** [siggame/webserver#91]
On the registration form, users need to know that if they check that they are not a full time student, that they will not be eligible to win prizes.  

On the team page, make it much more visible if a team is eligible to win prizes.  Enlarge the label.

One team consisted of 2 full time students, and 1 non-full time student.   At the tournament they got up and left because they came in with the idea that they would be eligible to win prizes.

**Comment by JustinKellogg** [comment]
if we know the id of the "is full time student question" we can watch that form/question. When the user enters an answer that would invalidate them (no, in this case) we can display some text or raise an alert to them, saying this would make them and their team ineligible. 

This wouldn't need any changes on the backend, and would just be a few javascript functions, but my concern is that it would be highly coupled with the specific questions. 

Thoughts?

**Comment by michaelwisely** [comment]
Only if we can do something without hard coding any values (ID or otherwise). I don't like the idea of relying on certain database entries containing certain information. 

The whole "Registration" bit in django-competition needs to be rethought. Surely there's an existing survey/questionnaire app for Django that would allow us to provide "help" or "warning" fields for questions like that.

**Comment by JustinKellogg** [comment]
Yeah, the only way I could see doing it with the existing implementation was hard coding id's (because each form has the id prefix)...which yeah, no bueno.

**Comment by jonsimington** [comment]
see #94

**Comment by michaelwisely** [comment]
I think this is cleared up now that we have official rules posted.
